<a href="https://colab.research.google.com/github/0layiw0la/Pytorch_learning/blob/main/FreeCodeCamp/Pytorch_fundamental_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# Introduction to Tensors

## Creating tensors

In [2]:
scalar = torch.tensor(7) # you know what a scalar is zero dim vector
scalar

tensor(7)

In [3]:
# To check dimensions of a tensor we use tensor.ndim
scalar.ndim

0

In [5]:
# Next looking at the shape of tensors (ofc only matters with 1+ dim tensors)

vector = torch.tensor([1,4,5])
vector.shape

torch.Size([3])

In [6]:
tens = torch.tensor([[
                        [[],[],[]],
                        [[],[],[]],
                        [[],[],[]]],
                      [
                          [[],[],[]],
                          [[],[],[]],
                          [[],[],[]]],
                      [
                          [[],[],[]],
                          [[],[],[]],
                          [[],[],[]]]
                     ])

tens.shape

torch.Size([3, 3, 3, 0])

## Random tensors
We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

``` Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...```

In [7]:
# creating a random tensor of size (3,3,3,1)
rand_tens = torch.rand(size=(3,3,3,1))
rand_tens, rand_tens.dtype,rand_tens.shape

(tensor([[[[0.0202],
           [0.8746],
           [0.6162]],
 
          [[0.9041],
           [0.4087],
           [0.9293]],
 
          [[0.9199],
           [0.9313],
           [0.9862]]],
 
 
         [[[0.2982],
           [0.7879],
           [0.3456]],
 
          [[0.1954],
           [0.5275],
           [0.6176]],
 
          [[0.6487],
           [0.6976],
           [0.9141]]],
 
 
         [[[0.1037],
           [0.0756],
           [0.5845]],
 
          [[0.8403],
           [0.1845],
           [0.7094]],
 
          [[0.3896],
           [0.3015],
           [0.0062]]]]),
 torch.float32,
 torch.Size([3, 3, 3, 1]))

### Zeros and ones

TO fill a tensor with zeros or ones we can just use torch.zeros() or torch.ones()

In [8]:
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

### Creating a range and tensors like

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.


Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [9]:
# range
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten
# notice it stops before end

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones,ten_zeros

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

# Tensor Datatypes